### ISSUE TITLE
This is a title

### ISSUE THREAD

**Issue by songweige** [rajcscw/google-word2vec-demo#1]
I think the last row of your code should be
`<# Getting word back from embedding
print(model.most_similar(positive=['car'], negative=[], topn=1))>`

**Comment by rajcscw** [comment]
Nope, I'm getting the word from the embedding (vector). So, it has to be `car` (which is a vector) not `'car'`(a string). Thanks though!

**Comment by songweige** [comment]
Ooops, I missed the above lines. Sorry about that.
Thx for replying me.
